# Generated by Django 5.1.4 on 2025-01-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('Sno', models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(default='', max_length=50)),
                ('Product_Dec', models.CharField(default='', max_length=1000)),
                ('Product_Price', models.IntegerField(default=0, max_length=15)),
            ],
        ),
    ]
