# Generated by Django 5.1.4 on 2025-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_Img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='Sno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
