# Generated by Django 5.1.4 on 2025-01-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0002_products_product_img_alter_products_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_Img',
            field=models.ImageField(upload_to='static/productImg'),
        ),
    ]
