# Generated by Django 5.1.4 on 2025-01-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0003_alter_products_product_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='ShopProducts',
        ),
    ]
