# Generated by Django 5.1.4 on 2025-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0004_rename_products_shopproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='Sno',
            field=models.IntegerField(default=0),
        ),
    ]
