# Generated by Django 5.1.4 on 2025-01-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0005_shopproducts_id_alter_shopproducts_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='Sno',
            field=models.IntegerField(),
        ),
    ]
