# Generated by Django 5.1.4 on 2025-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0006_alter_shopproducts_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='Sno',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
