# Generated by Django 5.1.4 on 2025-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0007_alter_shopproducts_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproducts',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='Sno',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
