# Generated by Django 5.1.4 on 2025-01-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0011_remove_order_amount_order_address_order_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default=0, max_length=12)),
                ('address', models.CharField(default='', max_length=500)),
                ('qut', models.CharField(default=0, max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('total_price', models.CharField(default=0, max_length=100000)),
                ('status', models.CharField(default='Pending', max_length=300, verbose_name='Payment Status')),
                ('razorpay_order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('razorpay_payment_id', models.CharField(max_length=70, verbose_name='Payment ID')),
                ('razorpay_signature', models.CharField(max_length=300, verbose_name='Signature ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ShopProducts',
            new_name='addShopProducts',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
