# Generated by Django 5.1.4 on 2025-01-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0013_rename_total_price_orders_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='razorpay_key_id',
            new_name='razorpay_payment_id',
        ),
    ]
