# Generated by Django 5.1.4 on 2025-01-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0015_alter_orders_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_amount',
            field=models.CharField(default=0, max_length=100000),
        ),
    ]
