# Generated by Django 5.1.4 on 2025-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0016_alter_orders_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='options',
            field=models.CharField(default='', max_length=50),
        ),
    ]
