# Generated by Django 5.1.4 on 2025-01-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0018_contact_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addshopproducts',
            name='Product_Img',
        ),
        migrations.AddField(
            model_name='addshopproducts',
            name='Product_Img_Five',
            field=models.ImageField(default='', upload_to='static/productImg'),
        ),
        migrations.AddField(
            model_name='addshopproducts',
            name='Product_Img_Four',
            field=models.ImageField(default='', upload_to='static/productImg'),
        ),
        migrations.AddField(
            model_name='addshopproducts',
            name='Product_Img_One',
            field=models.ImageField(default='', upload_to='static/productImg'),
        ),
        migrations.AddField(
            model_name='addshopproducts',
            name='Product_Img_Six',
            field=models.ImageField(default='', upload_to='static/productImg'),
        ),
        migrations.AddField(
            model_name='addshopproducts',
            name='Product_Img_Three',
            field=models.ImageField(default='', upload_to='static/productImg'),
        ),
        migrations.AddField(
            model_name='addshopproducts',
            name='Product_Img_Two',
            field=models.ImageField(default='', upload_to='static/productImg'),
        ),
    ]
