# Generated by Django 5.1.4 on 2025-01-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0019_remove_addshopproducts_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Five',
            field=models.ImageField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Four',
            field=models.ImageField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Six',
            field=models.ImageField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Three',
            field=models.ImageField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Two',
            field=models.ImageField(blank=True, default='', upload_to='static/productImg'),
        ),
    ]
