# Generated by Django 5.1.4 on 2025-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eisaalShop', '0020_alter_addshopproducts_product_img_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Five',
            field=models.FileField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Four',
            field=models.FileField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_One',
            field=models.FileField(default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Six',
            field=models.FileField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Three',
            field=models.FileField(blank=True, default='', upload_to='static/productImg'),
        ),
        migrations.AlterField(
            model_name='addshopproducts',
            name='Product_Img_Two',
            field=models.FileField(blank=True, default='', upload_to='static/productImg'),
        ),
    ]
